---
- name: Deploy Apache container
  hosts: prod
  become: true
  vars_files:
    - files/secrets/credentials.yml

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Run Apache container
      community.docker.docker_container:
        name: webapp
        image: httpd:latest
        ports:
          - "80:80"
