---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    prod:
      hosts:
        ec2_instance:
          ansible_host: 44.222.181.239
          ansible_user: ubuntu
