---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    prod:
      hosts:
        ec2_instance:
          ansible_host: 100.24.99.203
          ansible_user: ubuntu
